<a href="https://colab.research.google.com/github/Showside/AI-ML-practic/blob/main/Practic3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#1 Найти индексы ненулевых элементов в заданном массиве.

In [ ]:
data = np.random.randint(0,10, (15))
print(data)
data_notzero_args = np.where(data != 0)
print(np.nonzero(data))
print(data_notzero_args)

[3 9 4 3 6 2 1 5 8 6 6 4 3 0 9]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 14]),)
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 14]),)


#2 Создать nxn единичную матрицу.


In [ ]:
n = 5
one = np.eye(n)
print(one)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#3 Создать массив nxnxn со случайными значениями


In [ ]:
n = 3
data = np.random.random((n,n,n))
print(data)

[[[0.75077667 0.30346243 0.19854737]
  [0.87898327 0.82677812 0.03437998]
  [0.21184476 0.96209724 0.41221755]]

 [[0.21105102 0.50719704 0.16113494]
  [0.36297935 0.91879743 0.00654761]
  [0.85026583 0.78283188 0.33776554]]

 [[0.13144058 0.84415492 0.50880981]
  [0.92527198 0.16725965 0.3484597 ]
  [0.71961944 0.88290006 0.80022442]]]


#4 Создать вектор (одномерный массив) размера n, заполненный нулями


In [ ]:
n = 5
data = np.zeros(n)
print(data)

[0. 0. 0. 0. 0.]


#5 Создать вектор размера 1n, заполненный нулями, но пятый элемент равен 1


In [ ]:
n = 7
data = np.zeros(n)
data[4] = 1
print(data)

[0. 0. 0. 0. 1. 0. 0.]


#6 Создать вектор со значениями от n до m


In [ ]:
n,m = 3,10
data = np.arange(n,m+1)
print(data)

[ 3  4  5  6  7  8  9 10]


#7 Развернуть одномерный массив (первый становится последним)


In [ ]:
data_inv = data[::-1]
print(data_inv)

[10  9  8  7  6  5  4  3]


#8 Создать матрицу с 0 внутри, и 1 на границах


In [ ]:
n = 7
data = np.zeros((n,n))
data = np.asmatrix(data)
data[0,:], data[-1,:], data[:,0], data[:,-1] = 1, 1, 1, 1
print(data)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


#9 Создать nxn матрицу и заполнить её в шахматном порядке

In [ ]:
n = 5
data = np.zeros((n,n))
print(data.shape)
for i in range(n):
  for j in range(n):
    if (i % 2 == 1 and j % 2 == 1) or (i % 2 == 0 and j % 2 == 0):
      data[i][j] = 1
print(data)

(5, 5)
[[1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]]


#10 Заменить максимальный элемент на ноль


In [ ]:
data = np.random.randint(0,100, (15))
print(data)
data[data.argmax()] = 0
print(data)

[ 7 99 13 36 60 16 73 80  3 91  7 18 13 13 59]
[ 7  0 13 36 60 16 73 80  3 91  7 18 13 13 59]


#11 Найти ближайшее к заданному значению число в заданном массиве


In [ ]:
data = np.random.randint(0,100, (5,5))
x = 24
print(data)
diff = [abs(i - x) for i in data]
diff = np.array(diff)
data = data.reshape(25)
nearest = data[diff.argmin()]
print(f"Ближайшее к {x} число {nearest}")

[[17 25 53 51 72]
 [80 35 79 47 15]
 [44 31 50 18 76]
 [72 32 42 19 76]
 [88 50 40 17  1]]
Ближайшее к 24 число 25


#12 Дан четырехмерный массив, посчитать сумму по последним двум осям


In [ ]:
data = np.random.randint(0,100,(3,3,3,3))
print(data.sum(axis=-1)+data.sum(axis=-2))
#print(data)

[[[296 247 397]
  [434 194 238]
  [415 225 322]]

 [[439 275 338]
  [226 193 287]
  [267 261 200]]

 [[260 330 242]
  [236 450 326]
  [146 316 346]]]


#13 Определить, есть ли в двумерном массиве нулевые столбцы


In [ ]:
#data = np.random.rand(5,5)
data = np.array([
    [0,1,2,3,4],
    [0,1,2,3,4],
    [0,1,2,3,4],
    [0,1,2,3,4],
    [0,1,2,3,4],
])
print(data)
compare_mask = data == 0
count = 0
datat = data.T
for j in range(np.shape(datat)[0]):
  if np.all(datat[j]==0):
    count += 1
if count != 0:
  print("Нулевые столбцы имеются")
else:
  print("Нулевых столбцов нет")


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
Нулевые столбцы имеются


#14 Отнять среднее из каждой строки в матрице


In [ ]:
n = 7
data = np.random.randint(0,30,(n,n))
data = np.asmatrix(data)
print(data, "\n")
for i in range(np.shape(data)[0]):
  print("Среднее значение в строке",i,data[i].mean().round())
  data[i] = data[i]-data[i].mean().round()
print("\n", data)

[[ 5  0  2 29  9 19 26]
 [12 21  2  6 24 15 12]
 [12 21 25 12 13  7 19]
 [27 23  4  9 25 15 27]
 [26 28 20  1  1  2 21]
 [ 4 20  3 29  2 18 16]
 [29 12 14  1 11  4  3]] 

Среднее значение в строке 0 13.0
Среднее значение в строке 1 13.0
Среднее значение в строке 2 16.0
Среднее значение в строке 3 19.0
Среднее значение в строке 4 14.0
Среднее значение в строке 5 13.0
Среднее значение в строке 6 11.0

 [[ -8 -13 -11  16  -4   6  13]
 [ -1   8 -11  -7  11   2  -1]
 [ -4   5   9  -4  -3  -9   3]
 [  8   4 -15 -10   6  -4   8]
 [ 12  14   6 -13 -13 -12   7]
 [ -9   7 -10  16 -11   5   3]
 [ 18   1   3 -10   0  -7  -8]]


#15 Создайте вектор с элементами от 10 до 50


In [ ]:
data = np.arange(10,51)
print(data)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#16 Создайте матрицу (5, 5), заполненую от 0 до 6


In [ ]:
data = np.random.randint(0,7,(5,5))
data = np.asmatrix(data)
print(data)

[[0 2 2 1 3]
 [2 5 0 4 1]
 [3 5 5 6 5]
 [1 4 6 5 5]
 [3 0 1 5 3]]


#17 Умножьте матрицу размерности (5, 3) на (3, 2)


In [ ]:
data1 = np.random.randint(0,7,(5,3))
data1 = np.asmatrix(data1)
data2 = np.random.randint(0,7,(3,2))
data2 = np.asmatrix(data2)
data3 = data1.dot(data2)
print(data1, "\n")
print(data2, "\n")
print(data3)

[[5 5 1]
 [5 4 3]
 [2 1 4]
 [0 4 0]
 [3 6 6]] 

[[6 1]
 [4 5]
 [3 2]] 

[[53 32]
 [55 31]
 [28 15]
 [16 20]
 [60 45]]


#18 Создайте матрицу (10, 10) так, чтобы на границе были 0, а внтури 1


In [ ]:
data = np.ones((10,10))
data = np.asmatrix(data)
data[0,:], data[-1,:], data[:,0], data[:,-1] = 0, 0, 0, 0
print(data)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#19 Для заданного числа найдите ближайший к нему элемент в векторе


In [ ]:
data = np.random.randint(0,100, (15))
x = 24
diff = [abs(i - x) for i in data]
diff = np.array(diff)
nearest = data[diff.argmin()]
print(data)
print(f"Ближайшее к {x} число {nearest}")

[ 9 47 85 25 47 42 37  1 43 56 99 54 31 80 81]
Ближайшее к 24 число 25


#20 Дан трёхмерный массив "Цветное изображение", содержащий изображение, размера (height, width, numChannels), а также вектор коэффициентов длины numChannels. Сложить каналы изображения с указанными весами, и вернуть результат в виде матрицы размера (height, width). Реальное изображение не считываем, заполняем трехмерный массив случайными значениями. Преобразуйте цветное изображение в оттенки серого, использовав коэффициенты np.array([0.299, 0.587, 0.114]).

In [ ]:
height, width, num_channels = 10, 10, 3
color_image = np.random.rand(height, width, num_channels)
grey = np.array([0.299, 0.587, 0.114])
gray_image = np.dot(color_image, grey)
#axis=0 * 0.299, axis=1 * 0.587, axis=2 *0.114

print("Результирующее изображение в оттенках серого:\n", gray_image)

Результирующее изображение в оттенках серого:
 [[0.59903284 0.41713888 0.56788625 0.77840041 0.46840834 0.38809493
  0.48710847 0.3146621  0.50269436 0.79974567]
 [0.42820351 0.58862425 0.55456588 0.59056056 0.26345486 0.63880152
  0.45360416 0.57021787 0.56831835 0.28705602]
 [0.16819343 0.48470916 0.69274545 0.28525534 0.56380677 0.46193372
  0.32464469 0.29109099 0.74552014 0.35298846]
 [0.47501063 0.70263557 0.52499652 0.3317502  0.23828338 0.60632942
  0.31744061 0.45939222 0.55517628 0.58539826]
 [0.49378965 0.76388371 0.58215402 0.4060477  0.2542649  0.65127924
  0.53344332 0.51451433 0.23400006 0.69274377]
 [0.67442375 0.56866738 0.51846862 0.77888593 0.55707241 0.42673791
  0.94152676 0.57486009 0.64929313 0.3264989 ]
 [0.55896436 0.76900273 0.44999626 0.47059207 0.54437046 0.31166141
  0.35276699 0.22927053 0.23581718 0.47725253]
 [0.44919113 0.53831421 0.79717676 0.82188271 0.52648085 0.46033139
  0.52951563 0.88103955 0.22582686 0.12159693]
 [0.10649422 0.62055441 0.7813057